/**
 * api/products_service.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiColorOption } from './apiColorOption';
import { ApiSKU } from './apiSKU';


export interface ApiProduct { 
    familyCode?: string;
    familyName?: string;
    manufacturer?: string;
    ratingsCount?: number;
    deviceRank?: number;
    colorOptions?: Array<ApiColorOption>;
    averageStarRating?: string;
    operatingSystem?: string;
    defaultSku?: string;
    skus?: Array<ApiSKU>;
}
